Python. Homework #4. Task #1. Мищенко Станислав Алексеевич
mi-sts/spbu_python_homeworks pull request #9
Opened 2022-04-06 19:56 UTC by mi-sts

2022-04-07 16:07 UTC, SpirinEgor requested changes
Всё работает -- супер, но пока какая-то вакханалия с методами и классами. Надо навести порядок:
1. За что отвечает Node? Что она в себе хранит, нужны ли ей методы и какие?
2. За что отвечает Treap? Какой у него интерфейс?

2022-04-07 16:07 UTC, SpirinEgor commented on src/hw4/treap/node.py
> +    key: object = 0
object? Давай generic тут нормально поиспользуем

2022-04-07 16:07 UTC, SpirinEgor commented on src/hw4/treap/node.py
> +    def set_child(self, child: Optional["Node"], side: ChildSide):
А нужна ли вот такая прослойка с доп функцией и енамом? В том же insert, например, присваивать напрямую было бы удобнее

2022-04-07 16:07 UTC, SpirinEgor commented on src/hw4/treap/node.py
> +    def get_child(self, side: ChildSide) -> Optional["Node"]:
Как и тут, гораздо легче сразу написать `node.left`, чем вызывать функцию какую-то

2022-04-07 16:07 UTC, SpirinEgor commented on src/hw4/treap/node.py
> +@dataclass
Что-то это не пахнет датаклассом, функциональности тут явно больше, чем в самом дереве.

Лично мне нравится делать вершину через dataclass, но тогда надо аккуратнее со всеми функциями быть -- им тут не место

2022-04-07 16:07 UTC, SpirinEgor commented on src/hw4/treap/treap.py
> +    def __getitem__(self, key) -> object:
Не надо такие тупые типы использовать, я даже не знаю как тут трактовать сигнатуру...

2022-04-07 16:07 UTC, SpirinEgor commented on src/hw4/treap/treap.py
> +            self.root = init_object
Я не могу пустое дерево создать получается? Что-то типа `treap = Treap()`

2022-04-07 16:07 UTC, SpirinEgor commented on src/hw4/treap/treap.py
> +    def __init__(self, init_object: Dict | Node):
Для объединения типов есть `Union`

2022-04-07 16:07 UTC, SpirinEgor commented on src/hw4/treap/treap.py
> +    def split(self, key: object) -> Tuple["Treap", "Treap"]:
А это вообще не должно быть частью публичного интерфейса дерева -- разрезание и мердж это промежуточные операции для балансировки дерева

2022-04-07 16:07 UTC, SpirinEgor commented on tests/hw4/treap/test_node.py
> +    7, 10, Node(5, 8, Node(-2, 7, None, Node(-1, 6))), Node(8, 9, None, Node(12, 5, Node(10, 3), Node(16, 2)))
Тут вот для наглядности можно было отступами отрисовать дерево, для более наглядного тестирования (если это возможно)

2022-04-07 17:39 UTC, mi-sts commented on src/hw4/treap/node.py
> +@dataclass
@SpirinEgor, изначально я начал писать реализацию в си-подобном стиле и вся логика находилась в классе дерева, когда вершины передавались в качестве аргументов. Потом я решил, что здесь лучше будут смотреться ООП-подход и поэтому вся логика съехала в вершину, а класс дерева стал своеобразной обёрткой. 

Я думал над тем, как это можно было бы улучшить, не превращая методы в статические функции, но пока единственное, что видится, это вынести key, value, left, right в отдельный датакласс. 

Класс Treap не получится объединить с Node, т.к. нам нужно инициализировать дерево с помощью словаря, а перенос логики из Node в Treap повлечёт за собой этот си-подобный стиль

2022-04-11 14:12 UTC, SpirinEgor commented on src/hw4/treap/node.py
> +@dataclass
Мыслишь абсолютно верно!

Не надо натягивать сову на глобус и делать из node -- treap. Пусть будет датакласс вершины, которая и хранит в себе key, priority, value, left, right. К этому можно добавить пару функций -- итератор,  __repr__.

Но о чём я говорю и ты понимаешь: появилось много с-подобного в этом классе, например, всякие вставки, удаления и тп это функции НАД вершиной, а не часть интерфейса вершины (нажимать кнопки на пульте -- задача пользователя, сам пульт лишь показывает какие кнопки есть). То есть по сути, надо чтобы Treap вызывал split над вершиной, а потом как-то по-умному склеивал.

Я бы предложил split и merge сделать глобальными в модуле функциями, можно добавить в название _, чтобы подчеркнуть локальность в рамках модуля. Тогда insert внутри Treap будет их вызывать и всё будет красиво.

Можем дополнительно обсудить.

2022-04-11 14:14 UTC, SpirinEgor commented
Я оставил выше комментарий по архитектуре, ознакомься, пожалуйста

2022-04-11 17:07 UTC, mi-sts commented on src/hw4/treap/node.py
> +@dataclass
Значит в классе Treap останется только insert, remove и всякие магические методы, которые как-то оперируют этими вершинами, единственная функция которых заключается в хранении данных и возможности как-то выводиться и предоставлять возможность итерации.

Я правильно понял, что всяческие операции это задача дерева, поэтому эти методы нужно переместить в Treap и изменить их так, чтобы передавать вершины как аргументы (то есть как раз проводить операции НАД вершиной)?

2022-04-14 10:25 UTC, SpirinEgor commented on src/hw4/treap/node.py
> +@dataclass
Ага, как-то так выходить.
У тебя выйдет что-то такое:
```python
class Treap:
    ...
    def __setitem__(self, key, value):
        # necessary checks
        ...
        
        treap_left, treap_right = split(self.root, key)
        ...
        self.root = merge(...)
```

2022-04-16 07:53 UTC, mi-sts commented on src/hw4/treap/node.py
> +@dataclass
Поправил

2022-04-18 12:48 UTC, SpirinEgor reviewed
Всё супер, маленькая деталь: сейчас дерево довольно бесполезно, оно не предпологает хранение какой-то информации, как ассоциативный массив. Более того, если на ключ ещё можно наложить органичение Comparable, то делать такое на значение довольно странно.

Обычно это решается так: приоритет выбирается рандомно, под каждый ключ. А value --- просто некоторая хранимая информация в дереве

2022-04-18 12:48 UTC, SpirinEgor commented on src/hw4/treap/treap.py
> +def _find_in(node: Optional[Node], key: K) -> Optional[Node]:
Не уверен, что и это надо было выносить, но да ладно

2022-04-22 10:31 UTC, SpirinEgor approved these changes

2022-04-22 10:31 UTC, merged